In [9]:
# 初始化
import os
import sys
import cx_Oracle 
import pandas as pd

# 添加 oracle 客户端路径
sys.path.append('/Users/kai/instantclient_19_8')

# 创建 DSN
intern = cx_Oracle.makedsn('119.147.213.115', '1522', service_name='wktzorcl')
# 设置工作目录
os.chdir('/Users/kai/Desktop/qs')
def queryOracle(sql):
    # 创建连接
    conn = cx_Oracle.connect(user='wktz_intern01', password='wktz_intern01', dsn=intern)
    # 创建游标
    curs = conn.cursor()
    # 执行查询
    curs.execute(sql)
    # 返回查询结果
    data = curs.fetchall()
    # 获取列名
    columns = [i[0] for i in curs.description]
    # 将结果转换为DataFrame格式
    df = pd.DataFrame(data, columns=columns)
    # 关闭游标和连接
    curs.close()
    conn.close()
    
    return df

In [57]:
# 中国石化 测试
sql_1 = '''
SELECT SUBSTR(S_INFO_WINDCODE, 1, 6) as code, a.* FROM WKWD_SYNC.ashareeodprices a
where s_info_windcode like '600028%' and trade_dt > 20230601
order by trade_dt
'''
display(queryOracle(sql_1))

,CODE,OBJECT_ID,S_INFO_WINDCODE,TRADE_DT,CRNCY_CODE,S_DQ_PRECLOSE,S_DQ_OPEN,S_DQ_HIGH,S_DQ_LOW,S_DQ_CLOSE,...,S_DQ_ADJCLOSE,S_DQ_ADJFACTOR,S_DQ_AVGPRICE,S_DQ_TRADESTATUS,S_DQ_TRADESTATUSCODE,OPDATE,OPMODE,S_DQ_LIMIT,S_DQ_STOPPING,S_DQ_ADJCLOSE_BACKWARD
0,600028,{B0B755C2-0113-11EE-A126-782BCB400C61},600028.SH,20230602,CNY,6.49,6.53,6.60,6.47,6.49,...,25.47,3.924927,6.5156,交易,-1,2023-06-02 15:23:38,0,7.14,5.84,6.49
1,600028,{2C4D7F22-036F-11EE-A128-A4BADB2C279A},600028.SH,20230605,CNY,6.49,6.53,6.68,6.49,6.57,...,25.79,3.924927,6.5980,交易,-1,2023-06-05 15:18:45,0,7.14,5.84,6.57
2,600028,{55C752AB-0438-11EE-A127-842B2B441BB1},600028.SH,20230606,CNY,6.57,6.55,6.67,6.45,6.55,...,25.71,3.924927,6.5857,交易,-1,2023-06-06 15:16:28,0,7.23,5.91,6.55

In [63]:
# 维度
sql_2 = '''
select count(distinct(s_info_windcode)) as num_of_code, min(trade_dt), max(trade_dt), max(rownum) from WKWD_SYNC.ashareeodprices
'''
display(queryOracle(sql_2))

   NUM_OF_CODE MIN(TRADE_DT) MAX(TRADE_DT)  MAX(ROWNUM)
0         5400      20000104      20230606     15076250

In [156]:
# 查询拥有权限
sql_p = "SELECT * FROM user_tab_privs WHERE privilege = 'SELECT'"
df_p = queryOracle(sql_p)
display(df_p)
df_p.to_excel('可查.xlsx', index=False)

,GRANTEE,OWNER,TABLE_NAME,GRANTOR,PRIVILEGE,GRANTABLE,HIERARCHY
0,WKTZ_INTERN01,WKWD_SYNC,AINDEXEODPRICES,WKWD_SYNC,SELECT,NO,NO
1,WKTZ_INTERN01,WKWD_SYNC,ASHAREEODPRICES,WKWD_SYNC,SELECT,NO,NO

In [10]:
# 1. 获取所有股票代码
sql_get_all_code = '''
SELECT distinct(s_info_windcode) FROM WKWD_SYNC.ashareeodprices
'''
windcodes = queryOracle(sql_get_all_code)

In [ ]:
# 2. 获取所有股票的数据 并保存为csv
os.chdir('/Users/kai/Desktop/qs/_data_csv')
for i in windcodes['S_INFO_WINDCODE']:
    sql_temp = '''
    select distinct * from WKWD_SYNC.ashareeodprices where s_info_windcode = '{}' 
    order by trade_dt 
    '''.format(i)
    df_temp = queryOracle(sql_temp)
    # write a csv in the name of i
    df_temp.to_csv('{}.csv'.format(i), index=False, encoding='utf-8-sig')

os.chdir('/Users/kai/Desktop/qs')

In [168]:
# 换手率 from baostock
import baostock as bs

#### 登陆系统 ####
lg = bs.login()
# 显示登陆返回信息
# print('login respond error_code:'+lg.error_code)
# print('login respond  error_msg:'+lg.error_msg)

#### 获取沪深A股历史K线数据 ####
# 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
# 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
# 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg

# 整理股票代码格式： 600000.SH -> sh.600000


def windcode_to_bscode(windcode):
    if windcode[7] == 'S':
        return 'sz.' + windcode[0:6]
    elif windcode[7] == 'Z':
        return 'sh.' + windcode[0:6]
    else:
        return 'sh.' + windcode[0:6]


for i in windcodes['S_INFO_WINDCODE']:
    i_bs = windcode_to_bscode(i)
    rs = bs.query_history_k_data_plus(i_bs,
                                      "date,code,volume,amount,adjustflag,turn,tradestatus,isST",
                                      start_date='2000-01-01', end_date='2023-06-12',
                                      frequency="d", adjustflag="3")
    # print('query_history_k_data_plus respond error_code:'+rs.error_code)
    # print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

    #### 打印结果集 ####
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())
    result = pd.DataFrame(data_list, columns=rs.fields)

    #### 结果集输出到csv文件 ####
    result.to_csv("/Users/kai/Desktop/qs/turn/{}.csv".format(i), index=False)
    # print(result)

#### 登出系统 ####
bs.logout()

login success!
logout success!

In [28]:
# 计算月k数据

for i in windcodes['S_INFO_WINDCODE']:
    os.chdir('/Users/kai/Desktop/qs/data_csv')
    df_month = pd.read_csv('{}.csv'.format(i))
    os.chdir('/Users/kai/Desktop/qs/month')

    # 交易时间变为时间变量
    df_month['TRADE_DT'] = pd.to_datetime(
        df_month['TRADE_DT'], format='%Y%m%d')
    df_month.set_index('TRADE_DT', inplace=True)
    df_month_temp = pd.DataFrame(
        df_month[['S_DQ_OPEN', 'S_DQ_HIGH', 'S_DQ_LOW', 'S_DQ_CLOSE', 'S_DQ_VOLUME', 'S_DQ_AMOUNT']])

    # 月k数据
    df_month_temp = df_month_temp.resample('M').agg(
        {'S_DQ_OPEN': 'first', 'S_DQ_HIGH': 'max', 'S_DQ_LOW': 'min', 'S_DQ_CLOSE': 'last', 'S_DQ_VOLUME': 'sum', 'S_DQ_AMOUNT': 'sum'})
    df_month_temp.columns = ['open', 'high',
                            'low', 'close', 'volume', 'amount']

    # add a column 'mean' = amount / volume
    df_month_temp['mean'] = 10 * \
        df_month_temp['amount'] / df_month_temp['volume']

    df_month_temp.reset_index(inplace=True)
    df_month_temp.to_csv('{}.csv'.format(i), index=False, encoding='utf-8-sig')

In [17]:
# baostock换手率检查
# check if csvs in '/Users/kai/Desktop/qs/turn/' is smaller than 1 kb
os.chdir('/Users/kai/Desktop/qs/turn')
count = 0
for i in os.listdir():
    if os.path.getsize(i) < 1000:
        count += 1
        # print(i)
print(count)

2523

In [14]:
# wind换手率检查
# check if name of csvs in '/Users/kai/Desktop/qs/turn_wind/' is in original_name
original_name = pd.read_csv('/Users/kai/Desktop/qs/windcodes.csv')
os.chdir('/Users/kai/Desktop/qs/turn_wind')
count = 0
for i in os.listdir():
    if i[0:9] not in original_name['S_INFO_WINDCODE'].tolist():
        count += 1
        print(i)
print(count)

301383.SZ.CSV
688623.SH.CSV
301287.SZ.CSV
301355.SZ.CSV
836221.BJ.CSV
301232.SZ.CSV
301320.SZ.CSV
688472.SH.CSV
8

In [23]:
# 日k开盘价时间序列平稳性检验
from statsmodels.tsa.stattools import adfuller
count = 0
os.chdir('/Users/kai/Desktop/qs/data_csv')
for i in original_name['S_INFO_WINDCODE']:
    df_temp = pd.read_csv('{}.csv'.format(i))
    r = adfuller(df_temp['S_DQ_OPEN'])
    # 打印其中平稳的股票
    if r[1] < 0.05 and r[0] < r[4]['5%']:
        count += 1
print(count)

ValueError: sample size is too short to use selected regression component

In [ ]:
# 月k开盘价平稳性检验
from statsmodels.tsa.stattools import adfuller
count = 0
os.chdir('/Users/kai/Desktop/qs/month')
for i in original_name['S_INFO_WINDCODE']:
    df_temp = pd.read_csv('{}.csv'.format(i))
    r = adfuller(df_temp['S_DQ_OPEN'])
    # 打印其中平稳的股票
    if r[1] < 0.05 and r[0] < r[4]['5%']:
        count += 1
print(count)